services:
  apache:
    container_name: damp_apache
    build:
      context: ./apache
      args:
        USER_ID: ${USER_ID:-1000}
        USER_GROUP: ${USER_GROUP:-1000}
    ports:
      - 80:80
    # links:
    #   - db
    volumes:
      - './www:/var/www'
      - './log/apache:/var/log/apache2'
      - './vhost:/etc/apache2/sites-enabled'
      - './apache/startup.sh:/etc/apache2/startup.sh'
      - './apache/apache2.conf:/etc/apache2/apache2.conf'
  # db:
  #   container_name: damp_mysql
  #   image: mysql:8.4
  #   ports:
  #     - '3306:3306'
  #   environment:
  #     MYSQL_ROOT_PASSWORD: damp
  #   volumes:
  #     - './mysql:/var/lib/mysql'
  #   networks:
  #     - default
  # phpmyadmin:
  #   container_name: damp_phpmyadmin
  #   image: phpmyadmin/phpmyadmin
  #   links:
  #     - db:db
  #   ports:
  #     - 8080:80
  #   environment:
  #     MYSQL_ROOT_PASSWORD: damp
